# Config file for automatic testing at travis-ci.org

language: python
addons:
    postgresql: "9.3"

install: pip install tox coveralls

before_script:
    - psql -U postgres -c 'create database bpzaroundme;'
    - psql -U postgres -c 'create extension if not exists postgis;'
    - psql -U postgres -c 'create extension if not exists postgis_topology;'
    - psql -U postgres -c 'select postgis_lib_version();'

script: tox
env:
    - TOXENV=py26 DATABASE_URL="postgis://postgres@/bpzaroundme"
    - TOXENV=py27 DATABASE_URL="postgis://postgres@/bpzaroundme"
    - TOXENV=py33 DATABASE_URL="postgis://postgres@/bpzaroundme"
    - TOXENV=py34 DATABASE_URL="postgis://postgres@/bpzaroundme"
    - TOXENV=style
    - TOXENV=docs

after_success: coveralls
